setDataProcessingOptions & setDataProcessingOptionsCountry & setDataProcessingOptionsState are being wrongly filtered
facebook/facebook-php-business-sdk pull request #526
Opened 2020-07-03 06:58 UTC by hhermsen

See https://developers.facebook.com/support/bugs/1963832433747979/

2020-09-14 04:33 UTC, shinde-rahul requested changes

2020-09-14 04:33 UTC, shinde-rahul commented on composer.json
> +  "name": "oraybeheer/facebook-php-business-sdk",
Please remove this file as this file should not be part of the PR. I believe you have added this to your testing needs.

2020-09-22 11:30 UTC, shinde-rahul commented
@hhermsen, there is conflict in `src/FacebookAds/Object/ServerSide/Event.php`, please resolve the same.

2021-05-08 08:12 UTC, Ayguna05 approved these changes

2021-05-08 08:12 UTC, Ayguna05 approved these changes

2022-10-28 06:32 UTC, closed without merging